---
title: "R-Ladies test"
author: "DL"
date: '2021-01-21'
output: 
  html_document:
    toc: yes
    toc_float:
      collapse: no
    fig_caption: yes
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = 'figures/', cache = TRUE)
```

```{r libraries, include = FALSE}
library(tidyverse)
library(vegan)
```

```{r read-data}
counts <- read_tsv(
  'data/ampliseq_results/abundance_table/unfiltered/feature-table.tsv',
  skip = 1,
  col_types = cols(.default = col_double(), `#OTU ID` = col_character())
) %>%
  rename(asv = `#OTU ID`) %>%
  pivot_longer(2:ncol(.), names_to = 'sample', values_to = 'count') %>%
  group_by(sample) %>% mutate(relab = count/sum(count)) %>% ungroup()
samples <- read_tsv('data/samples.tsv', col_types = 'cccDc')
taxa <- read_tsv('data/ampliseq_results/taxonomy/taxonomy.tsv', col_types = 'ccd') %>%
  transmute(asv = `Feature ID`, t = str_remove_all(Taxon, 'D_[0-9]__'), confidence = Confidence) %>%
  separate(t, c('domain', 'phylum', 'class', 'order', 'family', 'genus', 'species'), sep = ';', fill = 'right') %>%
  semi_join(counts, by = 'asv')
```

```{r}
counts %>%
  group_by(sample) %>% mutate(r = rank(desc(relab), ties.method = 'random')) %>%
  filter(r < 100) %>%
  ggplot(aes(r, relab, colour = sample)) +
  geom_line(aes(group = sample)) +
  #scale_y_log10() +
  theme(legend.position = 'none')
```

```{r nmds, include = FALSE}
nmds <- counts %>% select(sample, asv, relab) %>%
  pivot_wider(names_from = asv, values_from = relab, values_fill = 0) %>%
  data.frame() %>% column_to_rownames('sample') %>%
  metaMDS()
```

```{r nmds-plot}
nmds$points %>% data.frame() %>% rownames_to_column('sample') %>%
  inner_join(samples, by = 'sample') %>%
  mutate(month = lubridate::month(date) %>% as.character()) %>%
  ggplot(aes(MDS1, MDS2, colour = month, shape = lubridate::year(date) %>% as.character())) +
  scale_shape_discrete('Year') +
  geom_point()
```

```{r core-microbiome}
counts %>%
  filter(count > 0) %>%
  count(asv, name = 'presence') %>%
  mutate(presence = floor(presence/96 * 20)) %>%
  count(presence) %>%
  arrange(desc(presence)) %>%
  mutate(cs = cumsum(n)) %>%
  ggplot(aes(presence * 5, cs)) +
  geom_line()
```

